project:
  type: website
  output-dir: docs

website:
  title: "Patricia Park"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources
      - href: Blog_file.qmd
        text: Blogs

format:
  html:
    theme: 
      light: Morph
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: source

