project:
  type: website
  output-dir: docs

website:
  title: "Patricia Park"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources
    right:
      - href: resume/resume_no_number.pdf
        text: CV
  page-footer: 
    background: light
    left: "Copyright 2023, Patricia Park"


format:
  html:
    theme: styles.scss
      #light: Morph
      #dark: solar
    #css: styles.css
    mainfont: Fira Sans
    toc: true
    page-layout: full

editor: source

