---
title: "Los Angeles County's history with HOLC grade inequality"
description: "A brief view of how HOLC grading propelled the inequality in Los Angeles County"
author:
  - name: Patty Park
    url: https://p-park6.github.io/
    #orcid
    affiliation: MEDS
    affiliation-url: https://bren.ucsb.edu/masters-programs/master-environmental-data-science
date: 12-15-2023
categories: 
  - R
  - MEDS
  - Geospatial
bibliography: ../references.bib
citation: 
  url: https://p-park6.github.io/blog/2023-12-15-la-holc-grade-inequality/
#image: images/image name
#draft: true
---

# Overview

During the 1930's the Home Owners' Loan Corporation (HOLC), as part of the New Deal, rated neighborhoods based on their perceived safety for real estate investment. Their ranking system, (A (green), B (blue), C (yellow), D (red)) was then used to block access to loans for home ownership. While it was used to promote financial stimulation, it consequentially has been used for racial segregation, a history that is still visible in the United states. Informally known as "redlining", this practice has had widely-documented consequences not only for community wealth, but also health.[@gee2008] Redlined neighborhoods have less greenery[@nardone2021] and are hotter than other neighborhoods.[@hoffman2020]

The National Community Reinvestment Coalition released a document highlighting what the redlining community is, how it has affected certain communities, and the potential impact gentrification has on these communities. [^1] This study was able to take a deep dive into how this segregation impacts minority groups and the lack of investment in these communities to bring positive change.

This blog will cover a number of analysis including:

-   Various environmental factors that can impact a community's wellbeing
-   How many census block group sites are in these redlining areas
-   Impact on recreational activities based on HOLC grade groups


[^1]: Michell, B., & Franco, J. (2018, March 20). HOLC “redlining” maps: The persistent structure of segregation and economic inequality. https://ncrc.org/holc/ ↩